version: '3.7'
services:
  mongodb:
    container_name: "mongodb"
    image: mongo:4.4
    hostname: mongodb
    restart: always
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_USER=aboba
      - MONGO_PASSWORD=aboba
      - MONGO_DATABASE=medvezhiy-ugol
    ports:
      - 27017:27017
    networks:
      - med-ugol
  db:
    image: postgres
    hostname: db
    ports:
      - "6432:5432"  
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment: 
        - POSTGRES_DB=medvezhiy-ugol
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
    restart: always
    container_name: "db"
    networks:
      - med-ugol
  web:
    build:
      context: .
      dockerfile: ./Docker/web/Dockerfile
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - db
      - mongodb
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:6432/medvezhiy-ugol
      - SERVER_PORT=80
    container_name: prod_api
    restart: always
    networks:
      - med-ugol
  redis:
    image: 'redis:6.0.3'
    ports:
      - 6379:6379
    environment:
        - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - med-ugol
networks:
  med-ugol:
    name: med-ugol-network
volumes:
  postgres-data:
  mongo-data:
