"""empty message

Revision ID: 6b8e93cad24d
Revises: 
Create Date: 2023-02-14 23:29:11.995382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b8e93cad24d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nickname', sa.VARCHAR(length=30), nullable=False),
    sa.Column('name', sa.VARCHAR(length=15), nullable=False),
    sa.Column('user_type', sa.VARCHAR(length=15), nullable=False),
    sa.Column('surname', sa.VARCHAR(length=20), nullable=False),
    sa.Column('phone', sa.CHAR(length=12), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__users')),
    sa.UniqueConstraint('id', name=op.f('uq__users__id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
